(() => {
  const code = window.__RANDOM_PICKER_LANG__ || new URLSearchParams(location.search).get('lang') || location.pathname.split('/').filter(Boolean)[0] || 'ko';
  const N={ko:'한국어',en:'English',ja:'日本語',es:'Español',zh:'中文',fr:'Français',de:'Deutsch',pt:'Português',id:'Bahasa Indonesia',hi:'हिन्दी',pl:'Polski',it:'Italiano',nl:'Nederlands',tr:'Türkçe',vi:'Tiếng Việt',th:'ไทย',ar:'العربية'};
  if(!N[code]) return;
  const L={
    en:{name:'Random Picker',reset:'Reset',hero:'How should we<br>pick today?',tag:'Random result, your choice of method.',picker:'🎯 Picker Games',tools:'🎲 Game Tools',method:'Pick a method',games:['Ladder','Wheel','Draw','Pinball','Race','Capsule','Slot','Bomb'],number:'Number',nameMode:'Name',people:'People',unit:'people',auto:'Participants are created automatically from No. 1.',pname:'Participant names',nguide:'2–100 people · separate with commas or line breaks',sample:'Example',pick:'Number to pick',result:'Result',winner:'Winner',rank:'Rank',custom:'Custom result',start:'Start',remaining:'Candidates left',show:'Show result now',drawResult:'Pick result',repick:'Pick again from everyone',exclude:'Exclude winners & pick again',toolIntro:'Use these instantly for gatherings and board games.',toolNames:['Dice','Yut','Coin','Order','Teams'],roll:'Roll dice',throwYut:'Throw Yut',flip:'Flip coin',shuffle:'Shuffle order',makeTeams:'Make teams',count:'Count',teamCount:'Teams',front:'Heads',back:'Tails',total:'Total',language:'Language',soundOn:'Turn sound on',soundOff:'Turn sound off',complete:'Complete',all:'All',ready:'Ready',stop:'Stop',next:'Next',pass:'Pass it on',check:'Check the settings and try again.',infoTitle:'Pick anyone with 8 different methods',infoBody:'Enter numbers or names, choose one of eight picker games, and get a random result without signing up. You can pick again from everyone or exclude previous winners.',toolsTitle:'5 handy game tools',toolsBody:'Roll up to six dice, throw Yut, flip a coin, randomize an order, or divide participants into balanced teams.',privacyTitle:'Your input stays in your browser',privacyBody:'Names and entries are processed in the current browser and are not sent to the server. Random selection uses the browser’s cryptographic random generator.',faqTitle:'FAQ',faqBody:'Number mode creates participants automatically. Name mode accepts commas or line breaks. The same full picker and game tools work on mobile and desktop.',footer:['About','How to use','Privacy','Terms','Contact'],placeholder:'Enter participant names',orderPrompt:'Set a random order',teamPrompt:'Split into teams'},
    ja:{name:'ランダム抽選',reset:'リセット',hero:'今日はどうやって<br>選ぶ？',tag:'結果はランダム、方法は自由。',picker:'🎯 抽選ゲーム',tools:'🎲 ゲームツール',method:'抽選方法',games:['あみだくじ','ルーレット','くじ引き','ピンボール','レース','カプセル','スロット','爆弾'],number:'番号',nameMode:'名前',people:'人数',unit:'人',auto:'参加者は1番から自動で作成されます。',pname:'参加者名',nguide:'2〜100人 · カンマまたは改行で区切る',sample:'例',pick:'抽選人数',result:'結果',winner:'当選',rank:'順位',custom:'結果を入力',start:'開始',remaining:'残りの候補',show:'結果をすぐ表示',drawResult:'抽選結果',repick:'全員からもう一度抽選',exclude:'当選者を除いて再抽選',toolIntro:'集まりやボードゲームですぐ使えます。',toolNames:['サイコロ','ユンノリ','コイン','順番','チーム分け'],roll:'サイコロを振る',throwYut:'ユンノリを投げる',flip:'コインを投げる',shuffle:'順番をシャッフル',makeTeams:'チーム分け',count:'個数',teamCount:'チーム数',front:'表',back:'裏',total:'合計',language:'言語',soundOn:'効果音をオン',soundOff:'効果音をオフ',complete:'完了',all:'全体',ready:'準備',stop:'停止',next:'次へ',pass:'次の人へ',check:'設定を確認してもう一度お試しください。',infoTitle:'8つの方法で好きな人を抽選できます',infoBody:'番号または名前を入力し、8つの抽選ゲームから好きな方法を選べます。登録不要で、全員から再抽選したり当選者を除いて再抽選したりできます。',toolsTitle:'ゲーム進行に使える5つのツール',toolsBody:'最大6個のサイコロ、ユンノリ、コイン、順番決め、チーム分けを1つの画面で使えます。',privacyTitle:'入力内容はこのブラウザ内でのみ使用',privacyBody:'名前や入力内容は現在のブラウザ内で処理され、サーバーには送信されません。抽選にはブラウザの暗号学的乱数を使います。',faqTitle:'よくある質問',faqBody:'番号モードは参加者を自動作成し、名前モードはカンマまたは改行に対応します。同じ完全版をスマートフォンとPCで利用できます。',footer:['サービス紹介','使い方','プライバシー','利用規約','お問い合わせ'],placeholder:'参加者名を入力',orderPrompt:'順番を決める',teamPrompt:'チームを分ける'},
    es:{name:'Selector aleatorio',reset:'Reiniciar',hero:'¿Cómo elegimos<br>hoy?',tag:'Resultado aleatorio, método a tu gusto.',picker:'🎯 Juegos de sorteo',tools:'🎲 Herramientas de juego',method:'Método de sorteo',games:['Escalera','Ruleta','Sorteo','Pinball','Carrera','Cápsula','Tragaperras','Bomba'],number:'Número',nameMode:'Nombre',people:'Personas',unit:'personas',auto:'Los participantes se crean automáticamente desde el n.º 1.',pname:'Nombres de participantes',nguide:'2–100 personas · separa con comas o saltos de línea',sample:'Ejemplo',pick:'Cantidad a elegir',result:'Resultado',winner:'Ganador',rank:'Puesto',custom:'Resultado personalizado',start:'Iniciar',remaining:'Candidatos restantes',show:'Mostrar resultado ahora',drawResult:'Resultado del sorteo',repick:'Volver a elegir entre todos',exclude:'Excluir ganadores y volver a elegir',toolIntro:'Úsalas al instante en reuniones y juegos de mesa.',toolNames:['Dados','Yut','Moneda','Orden','Equipos'],roll:'Lanzar dados',throwYut:'Lanzar Yut',flip:'Lanzar moneda',shuffle:'Mezclar orden',makeTeams:'Crear equipos',count:'Cantidad',teamCount:'Equipos',front:'Cara',back:'Cruz',total:'Total',language:'Idioma',soundOn:'Activar sonido',soundOff:'Desactivar sonido',complete:'Completado',all:'Todos',ready:'Listo',stop:'Detener',next:'Siguiente',pass:'Pásalo',check:'Revisa la configuración e inténtalo de nuevo.',infoTitle:'Elige con 8 métodos diferentes',infoBody:'Introduce números o nombres y elige entre ocho juegos de sorteo. No hace falta registrarse; puedes repetir entre todos o excluir a los ganadores anteriores.',toolsTitle:'5 herramientas para jugar',toolsBody:'Lanza hasta seis dados, juega al Yut, lanza una moneda, ordena participantes al azar o crea equipos equilibrados.',privacyTitle:'Tus datos se quedan en el navegador',privacyBody:'Los nombres y entradas se procesan en el navegador actual y no se envían al servidor. La selección usa el generador aleatorio criptográfico del navegador.',faqTitle:'Preguntas frecuentes',faqBody:'El modo Número crea participantes automáticamente. El modo Nombre acepta comas o saltos de línea. La misma versión completa funciona en móvil y PC.',footer:['Acerca de','Cómo usar','Privacidad','Términos','Contacto'],placeholder:'Introduce nombres de participantes',orderPrompt:'Crear un orden aleatorio',teamPrompt:'Dividir en equipos'},
    zh:{name:'随机抽选',reset:'重置',hero:'今天<br>怎么抽？',tag:'结果随机，方式随你。',picker:'🎯 抽选游戏',tools:'🎲 游戏工具',method:'抽选方式',games:['梯子','转盘','抽签','弹珠','竞赛','胶囊','老虎机','炸弹'],number:'编号',nameMode:'姓名',people:'人数',unit:'人',auto:'参与者将从1号开始自动生成。',pname:'参与者姓名',nguide:'2–100人 · 用逗号或换行分隔',sample:'示例',pick:'抽取人数',result:'结果',winner:'中奖',rank:'名次',custom:'自定义结果',start:'开始',remaining:'剩余候选',show:'立即查看结果',drawResult:'抽选结果',repick:'从全部人员重新抽取',exclude:'排除中奖者后重抽',toolIntro:'聚会和桌游都能直接使用。',toolNames:['骰子','柶戏','硬币','顺序','分组'],roll:'掷骰子',throwYut:'掷柶',flip:'抛硬币',shuffle:'随机排序',makeTeams:'分组',count:'数量',teamCount:'组数',front:'正面',back:'反面',total:'合计',language:'语言',soundOn:'开启音效',soundOff:'关闭音效',complete:'完成',all:'全部',ready:'准备',stop:'停止',next:'下一个',pass:'传给下一位',check:'请检查设置后重试。',infoTitle:'用8种方式随机选人',infoBody:'输入编号或姓名，从8种抽选游戏中选择喜欢的方式即可，无需注册。可以从全部人员重新抽取，也可以排除之前的中奖者。',toolsTitle:'5种实用游戏工具',toolsBody:'可同时掷最多6个骰子、玩柶戏、抛硬币、随机排序或把参与者平均分组。',privacyTitle:'输入内容只在当前浏览器中使用',privacyBody:'姓名和输入内容只在当前浏览器中处理，不会发送到服务器。随机选择使用浏览器提供的加密随机数。',faqTitle:'常见问题',faqBody:'编号模式会自动生成参与者；姓名模式支持逗号或换行。手机和电脑使用的是同一套完整功能。',footer:['服务介绍','使用方法','隐私政策','使用条款','联系'],placeholder:'输入参与者姓名',orderPrompt:'随机排序',teamPrompt:'随机分组'},
    fr:{name:'Sélecteur aléatoire',reset:'Réinitialiser',hero:'Comment choisir<br>aujourd’hui ?',tag:'Résultat aléatoire, méthode au choix.',picker:'🎯 Jeux de tirage',tools:'🎲 Outils de jeu',method:'Méthode de tirage',games:['Échelle','Roulette','Tirage','Flipper','Course','Capsule','Machine à sous','Bombe'],number:'Numéro',nameMode:'Nom',people:'Participants',unit:'personnes',auto:'Les participants sont créés automatiquement à partir du n° 1.',pname:'Noms des participants',nguide:'2 à 100 personnes · séparez par virgules ou retours à la ligne',sample:'Exemple',pick:'Nombre à tirer',result:'Résultat',winner:'Gagnant',rank:'Classement',custom:'Résultat personnalisé',start:'Démarrer',remaining:'Candidats restants',show:'Afficher le résultat',drawResult:'Résultat du tirage',repick:'Retirer parmi tout le monde',exclude:'Exclure les gagnants et retirer',toolIntro:'À utiliser immédiatement en réunion ou pour les jeux de société.',toolNames:['Dés','Yut','Pièce','Ordre','Équipes'],roll:'Lancer les dés',throwYut:'Lancer le Yut',flip:'Lancer la pièce',shuffle:'Mélanger l’ordre',makeTeams:'Créer les équipes',count:'Nombre',teamCount:'Équipes',front:'Face',back:'Pile',total:'Total',language:'Langue',soundOn:'Activer le son',soundOff:'Couper le son',complete:'Terminé',all:'Tous',ready:'Prêt',stop:'Arrêter',next:'Suivant',pass:'Passez au suivant',check:'Vérifiez les réglages et réessayez.',infoTitle:'Choisissez avec 8 méthodes différentes',infoBody:'Saisissez des numéros ou des noms puis choisissez l’un des huit jeux de tirage. Sans inscription, vous pouvez recommencer avec tout le monde ou exclure les gagnants précédents.',toolsTitle:'5 outils pratiques pour jouer',toolsBody:'Lancez jusqu’à six dés, jouez au Yut, lancez une pièce, créez un ordre aléatoire ou répartissez les participants en équipes équilibrées.',privacyTitle:'Vos saisies restent dans le navigateur',privacyBody:'Les noms et saisies sont traités dans le navigateur actuel et ne sont pas envoyés au serveur. Le tirage utilise le générateur aléatoire cryptographique du navigateur.',faqTitle:'Questions fréquentes',faqBody:'Le mode Numéro crée les participants automatiquement. Le mode Nom accepte les virgules et retours à la ligne. La même version complète fonctionne sur mobile et ordinateur.',footer:['À propos','Mode d’emploi','Confidentialité','Conditions','Contact'],placeholder:'Saisissez les noms des participants',orderPrompt:'Créer un ordre aléatoire',teamPrompt:'Répartir en équipes'},
    de:{name:'Zufallsauswahl',reset:'Zurücksetzen',hero:'Wie wählen wir<br>heute?',tag:'Zufälliges Ergebnis, freie Methode.',picker:'🎯 Auswahlspiele',tools:'🎲 Spielwerkzeuge',method:'Auswahlmethode',games:['Leiter','Roulette','Los','Flipper','Rennen','Kapsel','Spielautomat','Bombe'],number:'Nummer',nameMode:'Name',people:'Personen',unit:'Personen',auto:'Teilnehmende werden automatisch ab Nr. 1 erstellt.',pname:'Namen der Teilnehmenden',nguide:'2–100 Personen · mit Komma oder Zeilenumbruch trennen',sample:'Beispiel',pick:'Anzahl auswählen',result:'Ergebnis',winner:'Gewinner',rank:'Rang',custom:'Eigenes Ergebnis',start:'Start',remaining:'Verbleibende Kandidaten',show:'Ergebnis sofort anzeigen',drawResult:'Auswahlergebnis',repick:'Aus allen erneut wählen',exclude:'Gewinner ausschließen und neu wählen',toolIntro:'Direkt für Treffen und Brettspiele nutzbar.',toolNames:['Würfel','Yut','Münze','Reihenfolge','Teams'],roll:'Würfeln',throwYut:'Yut werfen',flip:'Münze werfen',shuffle:'Reihenfolge mischen',makeTeams:'Teams bilden',count:'Anzahl',teamCount:'Teams',front:'Kopf',back:'Zahl',total:'Summe',language:'Sprache',soundOn:'Ton einschalten',soundOff:'Ton ausschalten',complete:'Fertig',all:'Alle',ready:'Bereit',stop:'Stopp',next:'Weiter',pass:'Weitergeben',check:'Einstellungen prüfen und erneut versuchen.',infoTitle:'Mit 8 Methoden zufällig auswählen',infoBody:'Nummern oder Namen eingeben und eines von acht Auswahlspielen wählen. Ohne Anmeldung erneut aus allen wählen oder frühere Gewinner ausschließen.',toolsTitle:'5 praktische Spielwerkzeuge',toolsBody:'Bis zu sechs Würfel werfen, Yut spielen, eine Münze werfen, eine Reihenfolge auslosen oder Personen gleichmäßig auf Teams verteilen.',privacyTitle:'Eingaben bleiben im Browser',privacyBody:'Namen und Eingaben werden nur im aktuellen Browser verarbeitet und nicht an den Server gesendet. Für die Auswahl wird der kryptografische Zufallsgenerator des Browsers genutzt.',faqTitle:'Häufige Fragen',faqBody:'Im Nummernmodus werden Teilnehmende automatisch erstellt. Der Namensmodus akzeptiert Kommas oder Zeilenumbrüche. Mobil und Desktop nutzen dieselbe Vollversion.',footer:['Über uns','Anleitung','Datenschutz','Bedingungen','Kontakt'],placeholder:'Namen der Teilnehmenden eingeben',orderPrompt:'Zufällige Reihenfolge',teamPrompt:'In Teams aufteilen'},
    pt:{name:'Sorteador aleatório',reset:'Redefinir',hero:'Como vamos sortear<br>hoje?',tag:'Resultado aleatório, método à sua escolha.',picker:'🎯 Jogos de sorteio',tools:'🎲 Ferramentas de jogo',method:'Método de sorteio',games:['Escada','Roleta','Sorteio','Pinball','Corrida','Cápsula','Caça-níquel','Bomba'],number:'Número',nameMode:'Nome',people:'Pessoas',unit:'pessoas',auto:'Os participantes são criados automaticamente a partir do nº 1.',pname:'Nomes dos participantes',nguide:'2–100 pessoas · separe por vírgulas ou quebras de linha',sample:'Exemplo',pick:'Quantidade a sortear',result:'Resultado',winner:'Vencedor',rank:'Classificação',custom:'Resultado personalizado',start:'Iniciar',remaining:'Candidatos restantes',show:'Mostrar resultado agora',drawResult:'Resultado do sorteio',repick:'Sortear novamente entre todos',exclude:'Excluir vencedores e sortear de novo',toolIntro:'Use na hora em encontros e jogos de tabuleiro.',toolNames:['Dados','Yut','Moeda','Ordem','Times'],roll:'Rolar dados',throwYut:'Jogar Yut',flip:'Jogar moeda',shuffle:'Embaralhar ordem',makeTeams:'Dividir times',count:'Quantidade',teamCount:'Times',front:'Cara',back:'Coroa',total:'Total',language:'Idioma',soundOn:'Ativar som',soundOff:'Desativar som',complete:'Concluído',all:'Todos',ready:'Pronto',stop:'Parar',next:'Próximo',pass:'Passe adiante',check:'Confira as configurações e tente novamente.',infoTitle:'Sorteie com 8 métodos diferentes',infoBody:'Digite números ou nomes e escolha um dos oito jogos de sorteio. Sem cadastro, você pode sortear novamente entre todos ou excluir vencedores anteriores.',toolsTitle:'5 ferramentas úteis para jogos',toolsBody:'Role até seis dados, jogue Yut, lance uma moeda, sorteie a ordem ou divida participantes em times equilibrados.',privacyTitle:'Seus dados ficam no navegador',privacyBody:'Nomes e entradas são processados apenas no navegador atual e não são enviados ao servidor. O sorteio usa o gerador aleatório criptográfico do navegador.',faqTitle:'Perguntas frequentes',faqBody:'O modo Número cria participantes automaticamente. O modo Nome aceita vírgulas ou quebras de linha. A mesma versão completa funciona no celular e no PC.',footer:['Sobre','Como usar','Privacidade','Termos','Contato'],placeholder:'Digite os nomes dos participantes',orderPrompt:'Criar ordem aleatória',teamPrompt:'Dividir em times'},
    id:{name:'Pemilih Acak',reset:'Atur ulang',hero:'Mau pilih dengan cara apa<br>hari ini?',tag:'Hasil acak, cara pilihanmu.',picker:'🎯 Game Undian',tools:'🎲 Alat Game',method:'Cara memilih',games:['Tangga','Roda','Undian','Pinball','Balapan','Kapsul','Slot','Bom'],number:'Nomor',nameMode:'Nama',people:'Jumlah orang',unit:'orang',auto:'Peserta dibuat otomatis mulai dari nomor 1.',pname:'Nama peserta',nguide:'2–100 orang · pisahkan dengan koma atau baris baru',sample:'Contoh',pick:'Jumlah yang dipilih',result:'Hasil',winner:'Pemenang',rank:'Peringkat',custom:'Hasil khusus',start:'Mulai',remaining:'Kandidat tersisa',show:'Tampilkan hasil sekarang',drawResult:'Hasil undian',repick:'Pilih lagi dari semua peserta',exclude:'Kecualikan pemenang lalu pilih lagi',toolIntro:'Langsung gunakan untuk kumpul-kumpul dan board game.',toolNames:['Dadu','Yut','Koin','Urutan','Tim'],roll:'Lempar dadu',throwYut:'Lempar Yut',flip:'Lempar koin',shuffle:'Acak urutan',makeTeams:'Bagi tim',count:'Jumlah',teamCount:'Jumlah tim',front:'Kepala',back:'Ekor',total:'Total',language:'Bahasa',soundOn:'Nyalakan suara',soundOff:'Matikan suara',complete:'Selesai',all:'Semua',ready:'Siap',stop:'Berhenti',next:'Berikutnya',pass:'Teruskan',check:'Periksa pengaturan lalu coba lagi.',infoTitle:'Pilih secara acak dengan 8 cara',infoBody:'Masukkan nomor atau nama lalu pilih salah satu dari delapan game undian. Tanpa daftar, Anda bisa memilih ulang dari semua peserta atau mengecualikan pemenang sebelumnya.',toolsTitle:'5 alat game praktis',toolsBody:'Lempar hingga enam dadu, main Yut, lempar koin, acak urutan, atau bagi peserta menjadi tim yang seimbang.',privacyTitle:'Input tetap di browser Anda',privacyBody:'Nama dan input diproses di browser saat ini dan tidak dikirim ke server. Pemilihan menggunakan generator acak kriptografis browser.',faqTitle:'Pertanyaan umum',faqBody:'Mode Nomor membuat peserta otomatis. Mode Nama menerima koma atau baris baru. Versi lengkap yang sama berfungsi di ponsel dan desktop.',footer:['Tentang','Cara pakai','Privasi','Ketentuan','Kontak'],placeholder:'Masukkan nama peserta',orderPrompt:'Buat urutan acak',teamPrompt:'Bagi menjadi tim'},
    hi:{name:'रैंडम पिकर',reset:'रीसेट',hero:'आज कैसे<br>चुनें?',tag:'नतीजा रैंडम, तरीका आपकी पसंद।',picker:'🎯 पिकर गेम',tools:'🎲 गेम टूल',method:'चुनने का तरीका',games:['सीढ़ी','रूलेट','ड्रॉ','पिनबॉल','रेस','कैप्सूल','स्लॉट','बम'],number:'नंबर',nameMode:'नाम',people:'कुल लोग',unit:'लोग',auto:'प्रतिभागी नंबर 1 से अपने-आप बनते हैं।',pname:'प्रतिभागियों के नाम',nguide:'2–100 लोग · कॉमा या नई पंक्ति से अलग करें',sample:'उदाहरण',pick:'कितने चुनें',result:'परिणाम',winner:'विजेता',rank:'रैंक',custom:'कस्टम परिणाम',start:'शुरू',remaining:'बचे उम्मीदवार',show:'परिणाम अभी दिखाएँ',drawResult:'चयन परिणाम',repick:'सभी में से फिर चुनें',exclude:'विजेताओं को हटाकर फिर चुनें',toolIntro:'मिलने-जुलने और बोर्ड गेम में तुरंत इस्तेमाल करें।',toolNames:['पासा','युत','सिक्का','क्रम','टीम'],roll:'पासा फेंकें',throwYut:'युत फेंकें',flip:'सिक्का उछालें',shuffle:'क्रम मिलाएँ',makeTeams:'टीम बनाएँ',count:'गिनती',teamCount:'टीम',front:'हेड',back:'टेल',total:'कुल',language:'भाषा',soundOn:'ध्वनि चालू करें',soundOff:'ध्वनि बंद करें',complete:'पूरा',all:'सभी',ready:'तैयार',stop:'रोकें',next:'अगला',pass:'आगे दें',check:'सेटिंग जाँचकर फिर कोशिश करें।',infoTitle:'8 तरीकों से रैंडम चयन करें',infoBody:'नंबर या नाम डालें और आठ पिकर गेम में से तरीका चुनें। साइन-अप के बिना सभी में से दोबारा चुनें या पिछले विजेताओं को बाहर करें।',toolsTitle:'5 उपयोगी गेम टूल',toolsBody:'एक साथ छह पासे तक फेंकें, युत खेलें, सिक्का उछालें, क्रम रैंडम करें या प्रतिभागियों को बराबर टीमों में बाँटें।',privacyTitle:'आपका इनपुट ब्राउज़र में रहता है',privacyBody:'नाम और इनपुट इसी ब्राउज़र में प्रोसेस होते हैं और सर्वर पर नहीं भेजे जाते। चयन ब्राउज़र के क्रिप्टोग्राफिक रैंडम जनरेटर का उपयोग करता है।',faqTitle:'अक्सर पूछे जाने वाले सवाल',faqBody:'नंबर मोड प्रतिभागी अपने-आप बनाता है। नाम मोड कॉमा या नई पंक्ति स्वीकार करता है। मोबाइल और डेस्कटॉप पर वही पूर्ण संस्करण चलता है।',footer:['परिचय','कैसे उपयोग करें','गोपनीयता','शर्तें','संपर्क'],placeholder:'प्रतिभागियों के नाम दर्ज करें',orderPrompt:'रैंडम क्रम बनाएँ',teamPrompt:'टीमों में बाँटें'},
    pl:{name:'Losowy wybór',reset:'Resetuj',hero:'Jak dziś<br>losujemy?',tag:'Wynik losowy, metoda dowolna.',picker:'🎯 Gry losujące',tools:'🎲 Narzędzia do gry',method:'Metoda losowania',games:['Drabinka','Ruletka','Los','Pinball','Wyścig','Kapsuła','Slot','Bomba'],number:'Numer',nameMode:'Nazwa',people:'Liczba osób',unit:'osób',auto:'Uczestnicy są tworzeni automatycznie od numeru 1.',pname:'Nazwy uczestników',nguide:'2–100 osób · oddziel przecinkami lub nowymi wierszami',sample:'Przykład',pick:'Liczba do wylosowania',result:'Wynik',winner:'Zwycięzca',rank:'Miejsce',custom:'Własny wynik',start:'Start',remaining:'Pozostali kandydaci',show:'Pokaż wynik teraz',drawResult:'Wynik losowania',repick:'Losuj ponownie ze wszystkich',exclude:'Wyklucz zwycięzców i losuj ponownie',toolIntro:'Do użycia od razu na spotkaniach i przy grach planszowych.',toolNames:['Kości','Yut','Moneta','Kolejność','Drużyny'],roll:'Rzuć kośćmi',throwYut:'Rzuć Yut',flip:'Rzuć monetą',shuffle:'Losuj kolejność',makeTeams:'Podziel na drużyny',count:'Liczba',teamCount:'Drużyny',front:'Orzeł',back:'Reszka',total:'Suma',language:'Język',soundOn:'Włącz dźwięk',soundOff:'Wyłącz dźwięk',complete:'Gotowe',all:'Wszyscy',ready:'Gotowe',stop:'Stop',next:'Dalej',pass:'Podaj dalej',check:'Sprawdź ustawienia i spróbuj ponownie.',infoTitle:'Losuj na 8 różnych sposobów',infoBody:'Wpisz numery lub nazwy i wybierz jedną z ośmiu gier losujących. Bez rejestracji możesz losować ponownie ze wszystkich lub wykluczyć poprzednich zwycięzców.',toolsTitle:'5 praktycznych narzędzi do gry',toolsBody:'Rzuć maksymalnie sześcioma kośćmi, zagraj w Yut, rzuć monetą, wylosuj kolejność albo podziel uczestników na równe drużyny.',privacyTitle:'Dane pozostają w przeglądarce',privacyBody:'Nazwy i wpisane dane są przetwarzane tylko w bieżącej przeglądarce i nie są wysyłane na serwer. Losowanie korzysta z kryptograficznego generatora losowego.',faqTitle:'Najczęstsze pytania',faqBody:'Tryb Numer tworzy uczestników automatycznie. Tryb Nazwa przyjmuje przecinki lub nowe wiersze. Ta sama pełna wersja działa na telefonie i komputerze.',footer:['O serwisie','Jak używać','Prywatność','Warunki','Kontakt'],placeholder:'Wpisz nazwy uczestników',orderPrompt:'Wylosuj kolejność',teamPrompt:'Podziel na drużyny'},
    it:{name:'Selettore casuale',reset:'Reimposta',hero:'Come scegliamo<br>oggi?',tag:'Risultato casuale, metodo a scelta.',picker:'🎯 Giochi di estrazione',tools:'🎲 Strumenti di gioco',method:'Metodo di estrazione',games:['Scala','Roulette','Estrazione','Flipper','Gara','Capsula','Slot','Bomba'],number:'Numero',nameMode:'Nome',people:'Persone',unit:'persone',auto:'I partecipanti vengono creati automaticamente dal n. 1.',pname:'Nomi dei partecipanti',nguide:'2–100 persone · separa con virgole o a capo',sample:'Esempio',pick:'Quanti estrarre',result:'Risultato',winner:'Vincitore',rank:'Posizione',custom:'Risultato personalizzato',start:'Avvia',remaining:'Candidati rimasti',show:'Mostra subito il risultato',drawResult:'Risultato estrazione',repick:'Estrai di nuovo da tutti',exclude:'Escludi i vincitori e riestrai',toolIntro:'Utili subito per incontri e giochi da tavolo.',toolNames:['Dadi','Yut','Moneta','Ordine','Squadre'],roll:'Lancia i dadi',throwYut:'Lancia Yut',flip:'Lancia la moneta',shuffle:'Mescola ordine',makeTeams:'Crea squadre',count:'Numero',teamCount:'Squadre',front:'Testa',back:'Croce',total:'Totale',language:'Lingua',soundOn:'Attiva suono',soundOff:'Disattiva suono',complete:'Completato',all:'Tutti',ready:'Pronto',stop:'Ferma',next:'Avanti',pass:'Passa al prossimo',check:'Controlla le impostazioni e riprova.',infoTitle:'Scegli con 8 metodi diversi',infoBody:'Inserisci numeri o nomi e scegli uno degli otto giochi di estrazione. Senza registrazione puoi ripetere tra tutti o escludere i vincitori precedenti.',toolsTitle:'5 pratici strumenti di gioco',toolsBody:'Lancia fino a sei dadi, gioca a Yut, lancia una moneta, crea un ordine casuale o dividi i partecipanti in squadre equilibrate.',privacyTitle:'I dati restano nel browser',privacyBody:'Nomi e input vengono elaborati solo nel browser corrente e non inviati al server. La selezione usa il generatore casuale crittografico del browser.',faqTitle:'Domande frequenti',faqBody:'La modalità Numero crea i partecipanti automaticamente. La modalità Nome accetta virgole o righe nuove. La stessa versione completa funziona su mobile e desktop.',footer:['Informazioni','Come si usa','Privacy','Termini','Contatti'],placeholder:'Inserisci i nomi dei partecipanti',orderPrompt:'Crea ordine casuale',teamPrompt:'Dividi in squadre'},
    nl:{name:'Willekeurige kiezer',reset:'Reset',hero:'Hoe kiezen we<br>vandaag?',tag:'Willekeurig resultaat, methode naar keuze.',picker:'🎯 Trekspellen',tools:'🎲 Speltools',method:'Kiesmethode',games:['Ladder','Roulette','Loting','Pinball','Race','Capsule','Slot','Bom'],number:'Nummer',nameMode:'Naam',people:'Aantal personen',unit:'personen',auto:'Deelnemers worden automatisch gemaakt vanaf nr. 1.',pname:'Namen van deelnemers',nguide:'2–100 personen · scheid met komma’s of nieuwe regels',sample:'Voorbeeld',pick:'Aantal kiezen',result:'Resultaat',winner:'Winnaar',rank:'Rang',custom:'Eigen resultaat',start:'Start',remaining:'Resterende kandidaten',show:'Resultaat nu tonen',drawResult:'Trekresultaat',repick:'Opnieuw kiezen uit iedereen',exclude:'Winnaars uitsluiten en opnieuw kiezen',toolIntro:'Direct te gebruiken bij bijeenkomsten en bordspellen.',toolNames:['Dobbelstenen','Yut','Munt','Volgorde','Teams'],roll:'Dobbelstenen gooien',throwYut:'Yut gooien',flip:'Munt opgooien',shuffle:'Volgorde husselen',makeTeams:'Teams maken',count:'Aantal',teamCount:'Teams',front:'Kop',back:'Munt',total:'Totaal',language:'Taal',soundOn:'Geluid aan',soundOff:'Geluid uit',complete:'Klaar',all:'Alles',ready:'Gereed',stop:'Stop',next:'Volgende',pass:'Geef door',check:'Controleer de instellingen en probeer opnieuw.',infoTitle:'Kies willekeurig met 8 methoden',infoBody:'Voer nummers of namen in en kies één van acht trekspellen. Zonder account kun je opnieuw uit iedereen kiezen of eerdere winnaars uitsluiten.',toolsTitle:'5 handige speltools',toolsBody:'Gooi maximaal zes dobbelstenen, speel Yut, gooi een munt, maak een willekeurige volgorde of verdeel deelnemers eerlijk over teams.',privacyTitle:'Invoer blijft in je browser',privacyBody:'Namen en invoer worden alleen in de huidige browser verwerkt en niet naar de server gestuurd. De keuze gebruikt de cryptografische toevalsgenerator van de browser.',faqTitle:'Veelgestelde vragen',faqBody:'Nummermodus maakt deelnemers automatisch. Naammodus accepteert komma’s of nieuwe regels. Dezelfde volledige versie werkt op mobiel en desktop.',footer:['Over','Gebruiksaanwijzing','Privacy','Voorwaarden','Contact'],placeholder:'Voer namen van deelnemers in',orderPrompt:'Maak willekeurige volgorde',teamPrompt:'Verdeel in teams'},
    tr:{name:'Rastgele Seçici',reset:'Sıfırla',hero:'Bugün nasıl<br>seçelim?',tag:'Sonuç rastgele, yöntem sana kalmış.',picker:'🎯 Seçim Oyunları',tools:'🎲 Oyun Araçları',method:'Seçim yöntemi',games:['Merdiven','Rulet','Kura','Pinball','Yarış','Kapsül','Slot','Bomba'],number:'Numara',nameMode:'İsim',people:'Kişi sayısı',unit:'kişi',auto:'Katılımcılar 1 numaradan başlayarak otomatik oluşturulur.',pname:'Katılımcı adları',nguide:'2–100 kişi · virgül veya satır sonuyla ayırın',sample:'Örnek',pick:'Seçilecek kişi sayısı',result:'Sonuç',winner:'Kazanan',rank:'Sıra',custom:'Özel sonuç',start:'Başlat',remaining:'Kalan adaylar',show:'Sonucu şimdi göster',drawResult:'Seçim sonucu',repick:'Herkes arasından yeniden seç',exclude:'Kazananları çıkarıp yeniden seç',toolIntro:'Toplantı ve masa oyunlarında hemen kullanın.',toolNames:['Zar','Yut','Yazı tura','Sıra','Takımlar'],roll:'Zar at',throwYut:'Yut at',flip:'Yazı tura at',shuffle:'Sırayı karıştır',makeTeams:'Takım oluştur',count:'Adet',teamCount:'Takım sayısı',front:'Yazı',back:'Tura',total:'Toplam',language:'Dil',soundOn:'Sesi aç',soundOff:'Sesi kapat',complete:'Tamamlandı',all:'Tümü',ready:'Hazır',stop:'Durdur',next:'Sonraki',pass:'Devret',check:'Ayarları kontrol edip yeniden deneyin.',infoTitle:'8 farklı yöntemle rastgele seçin',infoBody:'Numara veya isim girip sekiz seçim oyunundan birini seçin. Kayıt olmadan herkesten yeniden seçim yapabilir veya önceki kazananları hariç tutabilirsiniz.',toolsTitle:'5 kullanışlı oyun aracı',toolsBody:'En fazla altı zar atın, Yut oynayın, yazı tura atın, sırayı rastgele belirleyin veya katılımcıları dengeli takımlara ayırın.',privacyTitle:'Girdiler tarayıcıda kalır',privacyBody:'İsimler ve girdiler yalnızca mevcut tarayıcıda işlenir ve sunucuya gönderilmez. Seçim tarayıcının kriptografik rastgele üretecini kullanır.',faqTitle:'Sık sorulanlar',faqBody:'Numara modu katılımcıları otomatik oluşturur. İsim modu virgül veya yeni satırı kabul eder. Aynı tam sürüm mobilde ve masaüstünde çalışır.',footer:['Hakkında','Nasıl kullanılır','Gizlilik','Koşullar','İletişim'],placeholder:'Katılımcı adlarını girin',orderPrompt:'Rastgele sıra oluştur',teamPrompt:'Takımlara ayır'},
    vi:{name:'Bộ chọn ngẫu nhiên',reset:'Đặt lại',hero:'Hôm nay chọn<br>thế nào?',tag:'Kết quả ngẫu nhiên, cách chọn tùy bạn.',picker:'🎯 Trò chơi chọn',tools:'🎲 Công cụ trò chơi',method:'Cách chọn',games:['Thang','Vòng quay','Bốc thăm','Pinball','Đua','Viên nang','Slot','Bom'],number:'Số',nameMode:'Tên',people:'Tổng số người',unit:'người',auto:'Người tham gia được tạo tự động từ số 1.',pname:'Tên người tham gia',nguide:'2–100 người · ngăn cách bằng dấu phẩy hoặc xuống dòng',sample:'Ví dụ',pick:'Số người cần chọn',result:'Kết quả',winner:'Người thắng',rank:'Xếp hạng',custom:'Kết quả tùy chỉnh',start:'Bắt đầu',remaining:'Ứng viên còn lại',show:'Hiện kết quả ngay',drawResult:'Kết quả chọn',repick:'Chọn lại từ tất cả',exclude:'Loại người thắng rồi chọn lại',toolIntro:'Dùng ngay cho buổi gặp mặt và trò chơi bàn.',toolNames:['Xúc xắc','Yut','Đồng xu','Thứ tự','Chia đội'],roll:'Tung xúc xắc',throwYut:'Ném Yut',flip:'Tung đồng xu',shuffle:'Xáo thứ tự',makeTeams:'Chia đội',count:'Số lượng',teamCount:'Số đội',front:'Ngửa',back:'Sấp',total:'Tổng',language:'Ngôn ngữ',soundOn:'Bật âm thanh',soundOff:'Tắt âm thanh',complete:'Hoàn tất',all:'Tất cả',ready:'Sẵn sàng',stop:'Dừng',next:'Tiếp',pass:'Chuyển cho người tiếp theo',check:'Kiểm tra cài đặt rồi thử lại.',infoTitle:'Chọn ngẫu nhiên bằng 8 cách',infoBody:'Nhập số hoặc tên rồi chọn một trong tám trò chơi. Không cần đăng ký; bạn có thể chọn lại từ tất cả hoặc loại những người đã thắng.',toolsTitle:'5 công cụ trò chơi tiện dụng',toolsBody:'Tung tối đa sáu xúc xắc, chơi Yut, tung đồng xu, xáo thứ tự hoặc chia người tham gia thành các đội cân bằng.',privacyTitle:'Dữ liệu chỉ ở trong trình duyệt',privacyBody:'Tên và nội dung nhập chỉ được xử lý trong trình duyệt hiện tại và không gửi lên máy chủ. Việc chọn dùng bộ sinh số ngẫu nhiên mật mã của trình duyệt.',faqTitle:'Câu hỏi thường gặp',faqBody:'Chế độ Số tự tạo người tham gia. Chế độ Tên nhận dấu phẩy hoặc xuống dòng. Cùng một bản đầy đủ hoạt động trên điện thoại và máy tính.',footer:['Giới thiệu','Cách dùng','Quyền riêng tư','Điều khoản','Liên hệ'],placeholder:'Nhập tên người tham gia',orderPrompt:'Tạo thứ tự ngẫu nhiên',teamPrompt:'Chia thành các đội'},
    th:{name:'สุ่มเลือก',reset:'รีเซ็ต',hero:'วันนี้จะสุ่ม<br>แบบไหนดี?',tag:'ผลลัพธ์สุ่ม วิธีเลือกตามใจคุณ',picker:'🎯 เกมสุ่ม',tools:'🎲 เครื่องมือเกม',method:'วิธีสุ่ม',games:['บันได','รูเล็ต','จับฉลาก','พินบอล','แข่ง','แคปซูล','สล็อต','ระเบิด'],number:'หมายเลข',nameMode:'ชื่อ',people:'จำนวนคน',unit:'คน',auto:'สร้างผู้เข้าร่วมอัตโนมัติตั้งแต่หมายเลข 1',pname:'ชื่อผู้เข้าร่วม',nguide:'2–100 คน · คั่นด้วยจุลภาคหรือขึ้นบรรทัดใหม่',sample:'ตัวอย่าง',pick:'จำนวนที่จะสุ่ม',result:'ผลลัพธ์',winner:'ผู้ชนะ',rank:'อันดับ',custom:'ผลลัพธ์กำหนดเอง',start:'เริ่ม',remaining:'ผู้สมัครที่เหลือ',show:'แสดงผลทันที',drawResult:'ผลการสุ่ม',repick:'สุ่มใหม่จากทุกคน',exclude:'ตัดผู้ชนะออกแล้วสุ่มใหม่',toolIntro:'ใช้ได้ทันทีสำหรับงานรวมกลุ่มและบอร์ดเกม',toolNames:['ลูกเต๋า','ยุต','เหรียญ','ลำดับ','แบ่งทีม'],roll:'ทอยลูกเต๋า',throwYut:'โยนยุต',flip:'โยนเหรียญ',shuffle:'สุ่มลำดับ',makeTeams:'แบ่งทีม',count:'จำนวน',teamCount:'จำนวนทีม',front:'หัว',back:'ก้อย',total:'รวม',language:'ภาษา',soundOn:'เปิดเสียง',soundOff:'ปิดเสียง',complete:'เสร็จ',all:'ทั้งหมด',ready:'พร้อม',stop:'หยุด',next:'ถัดไป',pass:'ส่งต่อ',check:'ตรวจสอบการตั้งค่าแล้วลองอีกครั้ง',infoTitle:'สุ่มเลือกได้ 8 วิธี',infoBody:'ใส่หมายเลขหรือชื่อ แล้วเลือกหนึ่งใน 8 เกมสุ่ม ไม่ต้องสมัครสมาชิก และสามารถสุ่มใหม่จากทุกคนหรือตัดผู้ชนะก่อนหน้าออกได้',toolsTitle:'5 เครื่องมือเกมที่ใช้ได้ทันที',toolsBody:'ทอยลูกเต๋าพร้อมกันสูงสุด 6 ลูก เล่นยุต โยนเหรียญ สุ่มลำดับ หรือแบ่งผู้เข้าร่วมเป็นทีมอย่างสมดุล',privacyTitle:'ข้อมูลอยู่ในเบราว์เซอร์ของคุณ',privacyBody:'ชื่อและข้อมูลที่กรอกจะประมวลผลในเบราว์เซอร์ปัจจุบันเท่านั้นและไม่ส่งไปยังเซิร์ฟเวอร์ การสุ่มใช้ตัวสร้างเลขสุ่มแบบเข้ารหัสของเบราว์เซอร์',faqTitle:'คำถามที่พบบ่อย',faqBody:'โหมดหมายเลขสร้างผู้เข้าร่วมอัตโนมัติ โหมดชื่อรองรับจุลภาคหรือขึ้นบรรทัดใหม่ เวอร์ชันเต็มเดียวกันใช้ได้ทั้งมือถือและคอมพิวเตอร์',footer:['เกี่ยวกับ','วิธีใช้','ความเป็นส่วนตัว','ข้อกำหนด','ติดต่อ'],placeholder:'กรอกชื่อผู้เข้าร่วม',orderPrompt:'สร้างลำดับแบบสุ่ม',teamPrompt:'แบ่งเป็นทีม'},
    ar:{name:'اختيار عشوائي',reset:'إعادة ضبط',hero:'كيف نختار<br>اليوم؟',tag:'النتيجة عشوائية والطريقة اختيارك.',picker:'🎯 ألعاب الاختيار',tools:'🎲 أدوات الألعاب',method:'طريقة الاختيار',games:['السلم','الروليت','القرعة','بينبول','سباق','كبسولة','سلوت','قنبلة'],number:'رقم',nameMode:'اسم',people:'عدد الأشخاص',unit:'أشخاص',auto:'يتم إنشاء المشاركين تلقائيًا بدءًا من الرقم 1.',pname:'أسماء المشاركين',nguide:'2–100 شخص · افصل بفواصل أو أسطر جديدة',sample:'مثال',pick:'عدد المختارين',result:'النتيجة',winner:'الفائز',rank:'الترتيب',custom:'نتيجة مخصصة',start:'ابدأ',remaining:'المرشحون المتبقون',show:'إظهار النتيجة الآن',drawResult:'نتيجة الاختيار',repick:'اختيار جديد من الجميع',exclude:'استبعاد الفائزين وإعادة الاختيار',toolIntro:'استخدمها فورًا في التجمعات وألعاب الطاولة.',toolNames:['نرد','يوت','عملة','ترتيب','فرق'],roll:'ارمِ النرد',throwYut:'ارمِ يوت',flip:'اقلب العملة',shuffle:'اخلط الترتيب',makeTeams:'قسّم الفرق',count:'العدد',teamCount:'عدد الفرق',front:'وجه',back:'ظهر',total:'المجموع',language:'اللغة',soundOn:'تشغيل الصوت',soundOff:'إيقاف الصوت',complete:'اكتمل',all:'الكل',ready:'جاهز',stop:'إيقاف',next:'التالي',pass:'مرّرها',check:'تحقق من الإعدادات وحاول مرة أخرى.',infoTitle:'اختر عشوائيًا بثماني طرق',infoBody:'أدخل أرقامًا أو أسماء واختر واحدة من ثماني ألعاب. دون تسجيل، يمكنك إعادة الاختيار من الجميع أو استبعاد الفائزين السابقين.',toolsTitle:'5 أدوات ألعاب مفيدة',toolsBody:'ارمِ حتى ستة أحجار نرد، العب يوت، اقلب عملة، أنشئ ترتيبًا عشوائيًا أو قسّم المشاركين إلى فرق متوازنة.',privacyTitle:'تبقى مدخلاتك في المتصفح',privacyBody:'تتم معالجة الأسماء والمدخلات داخل المتصفح الحالي فقط ولا تُرسل إلى الخادم. يستخدم الاختيار مولد الأرقام العشوائية التشفيري في المتصفح.',faqTitle:'الأسئلة الشائعة',faqBody:'وضع الرقم ينشئ المشاركين تلقائيًا، ووضع الاسم يقبل الفواصل أو الأسطر الجديدة. تعمل النسخة الكاملة نفسها على الهاتف والكمبيوتر.',footer:['حول الخدمة','طريقة الاستخدام','الخصوصية','الشروط','اتصل بنا'],placeholder:'أدخل أسماء المشاركين',orderPrompt:'إنشاء ترتيب عشوائي',teamPrompt:'تقسيم إلى فرق'}
  };
  if(code==='ko'){
    ensureSelector({language:'언어'});
    return;
  }
  const t=L[code]||L.en;
  document.documentElement.lang=code;
  document.documentElement.dir=code==='ar'?'rtl':'ltr';

  const q=s=>document.querySelector(s), qa=s=>[...document.querySelectorAll(s)];
  const text=(s,v)=>{const e=q(s);if(e)e.textContent=v};
  const attr=(s,k,v)=>{const e=q(s);if(e)e.setAttribute(k,v)};
  function ensureSelector(locale=t){
    document.querySelectorAll('#globalLanguageSwitch,#finalLanguageSwitch,#fullLanguageBox,#canonicalLanguageSwitch,#fullLanguageSelect,#canonicalLanguageSelect,#globalLanguageSelect,[data-global-language-switch],.global-language-switch,.language-switcher,.language-selector').forEach(el=>{const box=el.closest?.('#globalLanguageSwitch,#finalLanguageSwitch,#fullLanguageBox,label,div')||el;if(box?.id!=='globalLanguageSwitch')box.remove()});
    let box=q('#globalLanguageSwitch');
    if(!box){
      const header=q('header'); if(!header)return;
      box=document.createElement('label');box.id='globalLanguageSwitch';box.setAttribute('aria-label',locale.language||'Language');box.style.cssText='display:flex;align-items:center;gap:6px;margin-left:auto;flex:0 0 auto;white-space:nowrap';
      const globe=document.createElement('span');globe.textContent='🌐';globe.setAttribute('aria-hidden','true');
      const select=document.createElement('select');select.id='globalLanguageSelect';select.style.cssText='width:132px;height:38px;border:1px solid #e4ddd1;border-radius:11px;background:#fffdf8;padding:0 30px 0 10px;font:inherit;font-weight:800;color:#211d18';
      Object.entries(N).forEach(([c,label])=>{const o=document.createElement('option');o.value=c;o.textContent=label;o.selected=c===code;select.append(o)});
      select.addEventListener('change',()=>{location.href=select.value==='ko'?'/':`/${select.value}/`});
      box.append(globe,select);header.append(box);
    }
    box.setAttribute('aria-label',locale.language||'Language');
  }

  function staticUI(){
    const logo=q('.logo');if(logo)logo.textContent=t.name;
    text('#resetBtn',t.reset);const hero=q('.hero h1');if(hero)hero.innerHTML=t.hero;text('.hero p',t.tag);
    text('#showPicker',t.picker);text('#showTools',t.tools);text('.method-label',t.method);
    qa('.method .name').forEach((e,i)=>{if(t.games[i])e.textContent=t.games[i]});
    text('#numberTab',t.number);text('#nameTab',t.nameMode);
    text('#bombSettings .label span',t.games[7]+' '+(code==='en'?'time':code==='ja'?'時間':code==='es'?'tiempo':code==='zh'?'时间':code==='fr'?'durée':code==='de'?'Zeit':code==='pt'?'tempo':code==='id'?'waktu':code==='hi'?'समय':code==='pl'?'czas':code==='it'?'tempo':code==='nl'?'tijd':code==='tr'?'süre':code==='vi'?'thời gian':code==='th'?'เวลา':'الوقت'));
    text('#bombModeRandom',code==='en'?'Random':code==='ja'?'ランダム':code==='es'?'Aleatorio':code==='zh'?'随机':code==='fr'?'Aléatoire':code==='de'?'Zufällig':code==='pt'?'Aleatório':code==='id'?'Acak':code==='hi'?'रैंडम':code==='pl'?'Losowo':code==='it'?'Casuale':code==='nl'?'Willekeurig':code==='tr'?'Rastgele':code==='vi'?'Ngẫu nhiên':code==='th'?'สุ่ม':'عشوائي');
    text('#bombModeFixed',code==='en'?'Set time':code==='ja'?'時間設定':code==='es'?'Fijar tiempo':code==='zh'?'设置时间':code==='fr'?'Régler la durée':code==='de'?'Zeit einstellen':code==='pt'?'Definir tempo':code==='id'?'Atur waktu':code==='hi'?'समय सेट करें':code==='pl'?'Ustaw czas':code==='it'?'Imposta tempo':code==='nl'?'Tijd instellen':code==='tr'?'Süre ayarla':code==='vi'?'Đặt thời gian':code==='th'?'ตั้งเวลา':'ضبط الوقت');
    text('#totalField .label span',t.people);text('#numberMode .result-note',t.auto);text('#nameMode .label label',t.pname);text('#nameGuide',t.nguide);text('#sampleBtn',t.sample);attr('#names','placeholder',t.placeholder);
    text('#pickLabel',t.pick);text('.result-select-row .label-text',t.result);const opts=qa('#resultMode option');if(opts[0])opts[0].textContent=t.winner;if(opts[1])opts[1].textContent=t.rank;if(opts[2])opts[2].textContent=t.custom;text('#pickBtn',t.start);
    text('.remaining-head span',t.remaining);text('#showAllBtn',t.show);text('#resultKicker',t.drawResult);text('#repickBtn',t.repick);text('#excludeBtn',t.exclude);
    text('#gameToolsTitle',t.tools.replace(/^🎲\s*/,''));text('.tool-head p',t.toolIntro);qa('.tool-tab').forEach((e,i)=>{const span=e.querySelector('span');e.childNodes.forEach(n=>{if(n.nodeType===3)n.remove()});e.append(document.createTextNode(t.toolNames[i]||''));});
    const panels=qa('.tool-panel');if(panels[0]){panels[0].querySelector('h3').textContent=t.roll;panels[0].querySelector('.tool-desc').textContent=code==='en'?'Roll up to 6 dice at once.':t.toolsBody.split(/[.!。]/)[0]+'.';panels[0].querySelector('label').textContent=t.count;panels[0].querySelector('.tool-run').textContent=t.roll;panels[0].querySelector('.tool-result').textContent='🎲 '+t.start;}
    if(panels[1]){panels[1].querySelector('h3').textContent=t.throwYut;panels[1].querySelector('.tool-run').textContent=t.throwYut;panels[1].querySelector('.tool-result').textContent='🪵 '+t.start;}
    if(panels[2]){panels[2].querySelector('h3').textContent=t.flip;panels[2].querySelector('.tool-run').textContent=t.flip;}
    if(panels[3]){panels[3].querySelector('h3').textContent=t.orderPrompt;panels[3].querySelector('.tool-desc').textContent=t.nguide;attr('#orderNames','placeholder',t.placeholder);text('#makeOrder',t.shuffle);text('#orderResult',t.orderPrompt);}
    if(panels[4]){panels[4].querySelector('h3').textContent=t.teamPrompt;panels[4].querySelector('.tool-desc').textContent=t.toolsBody;attr('#teamNames','placeholder',t.placeholder);const lab=panels[4].querySelector('label');if(lab)lab.textContent=t.teamCount;text('#makeTeams',t.makeTeams);text('#teamResult',t.teamPrompt);}
    attr('#soundToggle','aria-label',q('#soundToggle')?.getAttribute('aria-pressed')==='true'?t.soundOff:t.soundOn);attr('#soundToggle','title',q('#soundToggle')?.getAttribute('aria-pressed')==='true'?t.soundOff:t.soundOn);
    attr('#numberTab','aria-label',t.number);attr('#nameTab','aria-label',t.nameMode);attr('#resultMode','aria-label',t.result);attr('#showPicker','aria-label',t.picker.replace(/^🎯\s*/,''));attr('#showTools','aria-label',t.tools.replace(/^🎲\s*/,''));
    qa('.unit').forEach(e=>{if(!e.closest('#bombFixedWrap'))e.textContent=t.unit});
    const info=q('.service-info');if(info)info.innerHTML=`<div class="service-copy" data-copy="picker"><h2>${t.infoTitle}</h2><p>${t.infoBody}</p><div class="game-tool-note"><strong>${t.privacyTitle}</strong><p>${t.privacyBody}</p></div></div><div class="service-copy" data-copy="tools" hidden><h2>${t.toolsTitle}</h2><p>${t.toolsBody}</p><div class="game-tool-note"><strong>${t.privacyTitle}</strong><p>${t.privacyBody}</p></div></div><details><summary>${t.faqTitle}</summary><p>${t.faqBody}</p></details>`;
    const links=qa('.footer-nav a');links.forEach((a,i)=>{if(t.footer[i])a.textContent=t.footer[i];const path=['about','guide','privacy','terms','contact'][i];if(path)a.href=`/${path}/?lang=${code}`});
    const fp=q('.site-footer p');if(fp)fp.textContent=t.privacyBody;
    ensureSelector(t);
  }

  function dynamicText(){
    const map=new Map([
      ['초기화',t.reset],['시작',t.start],['결과',t.result],['당첨',t.winner],['뽑기 결과',t.drawResult],['전체 결과',t.all+' '+t.result],['당첨 결과',t.winner+' '+t.result],['등수 결과',t.rank+' '+t.result],['전체에서 다시 뽑기',t.repick],['당첨자 제외하고 다시 뽑기',t.exclude],['바로 결과 보기',t.show],['완료',t.complete],['전체',t.all],['준비',t.ready],['룰렛 시작',t.games[1]+' '+t.start],['멈춤',t.stop],['다음 룰렛',t.next+' '+t.games[1]],['경주 시작',t.games[4]+' '+t.start],['레버 돌리기',t.start],['다음 캡슐',t.next+' '+t.games[5]],['슬롯 시작',t.games[6]+' '+t.start],['다음 슬롯',t.next+' '+t.games[6]],['폭탄 시작',t.games[7]+' '+t.start],['바로 터뜨리기',t.start],['준비되면 시작',t.ready],['걸렸습니다!',t.complete],['다시 시작',t.start],['미디어 음량을 확인해주세요',t.check],['현재 남은 후보',t.remaining],['주사위',t.toolNames[0]],['윷놀이',t.toolNames[1]],['동전',t.toolNames[2]],['순서',t.toolNames[3]],['팀 나누기',t.toolNames[4]],['주사위 굴리기',t.roll],['굴리기',t.roll],['윷 던지기',t.throwYut],['동전 던지기',t.flip],['순서 섞기',t.shuffle],['팀을 나눠보세요',t.teamPrompt],['앞면',t.front],['뒷면',t.back]
    ]);
    const safeSkip='.result-person,.winner,.ladder-pick,.race-name,.capsule-paper,.slot-item,.tag,.order-item,.team-box div,textarea,input';
    const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT);const nodes=[];while(walker.nextNode())nodes.push(walker.currentNode);
    for(const n of nodes){const p=n.parentElement;if(!p||p.matches('script,style')||p.closest(safeSkip))continue;const raw=n.nodeValue, s=raw.trim();if(map.has(s)){n.nodeValue=raw.replace(s,map.get(s));continue}
      if(/^\d+명$/.test(s))n.nodeValue=raw.replace(s,s.replace('명',' '+t.unit));
      else if(/^\d+팀$/.test(s))n.nodeValue=raw.replace(s,s.replace('팀',' '+t.toolNames[4]));
      else if(/^합계\s*\d+/.test(s))n.nodeValue=raw.replace(s,s.replace('합계',t.total));
      else if(/^[도개걸윷모]$/.test(s)){const y={도:'Do',개:'Gae',걸:'Geol',윷:'Yut',모:'Mo'};n.nodeValue=raw.replace(s,y[s]);}
      else if(/[가-힣]/.test(s) && p.closest('#hint,#stageStatus,#raceMiniStatus,#pinLiveText,.bomb-pass,.bomb-holder,.bomb-result,.race-result,.capsule-result,.slot-result,.round-result,.ladder-message,.toast')){
        let v=s.replaceAll('당첨',t.winner).replaceAll('완료',t.complete).replaceAll('전체',t.all).replaceAll('우승!',t.winner+'!').replaceAll('준비',t.ready).replace(/\d+명/g,m=>m.replace('명',' '+t.unit)).replace(/(\d+)위/g,'$1').replace(/(\d+)등/g,'$1 '+t.rank).replace(/(\d+)번째/g,'$1').replaceAll('아웃','OUT');
        if(/[가-힣]/.test(v))v=t.check;n.nodeValue=raw.replace(s,v);
      }
    }
    qa('[aria-label],[title],[placeholder]').forEach(el=>{
      for(const k of ['aria-label','title','placeholder']){const s=el.getAttribute(k);if(!s||!/[가-힣]/.test(s))continue;if(el.id==='soundToggle'){el.setAttribute(k,el.getAttribute('aria-pressed')==='true'?t.soundOff:t.soundOn);continue}if(el.id==='names'||el.id==='orderNames'||el.id==='teamNames'){el.setAttribute(k,t.placeholder);continue}if(map.has(s)){el.setAttribute(k,map.get(s));continue}const cleaned=s.replaceAll('당첨',t.winner).replaceAll('결과',t.result).replaceAll('이름',t.nameMode).replaceAll('번호',t.number);el.setAttribute(k,/[가-힣]/.test(cleaned)?t.check:cleaned);}
    });
    ensureSelector(t);
  }

  staticUI();dynamicText();
  let queued=false;const obs=new MutationObserver(()=>{if(queued)return;queued=true;queueMicrotask(()=>{queued=false;dynamicText()})});obs.observe(document.body,{subtree:true,childList:true,characterData:true,attributes:true,attributeFilter:['aria-label','title','aria-pressed']});
  document.addEventListener('click',e=>{if(e.target.closest('#sampleBtn'))setTimeout(()=>{const ta=q('#names');if(ta&&/[가-힣]/.test(ta.value)){const samples=code==='ja'?['佐藤','鈴木','高橋','田中','伊藤']:code==='zh'?['小明','小华','小李','小王','小陈']:['Alex','Sam','Taylor','Jordan','Casey','Morgan','Jamie','Riley','Avery','Cameron'];const n=Math.max(2,Math.floor(Number(q('#totalPeople')?.value)||8));ta.value=Array.from({length:n},(_,i)=>samples[i%samples.length]+(i>=samples.length?` ${Math.floor(i/samples.length)+1}`:'')).join('\n');ta.dispatchEvent(new Event('input',{bubbles:true}))}},0)},true);
})();
